// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtjbdfumggyaltfqdejj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0amJkZnVtZ2d5YWx0ZnFkZWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTM4MTMsImV4cCI6MjA2ODg4OTgxM30.O5ZWfusejVKgohA8-P3YRor6VC1XATvj41VxZ0TerTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});